runtime: python
env: flex
instance_class: F2
entrypoint: gunicorn -b :$PORT application:app
runtime_config:
  python_version: 3.7
resources:
 cpu: 8
 memory_gb: 50
 disk_size_gb: 60
readiness_check:
  app_start_timeout_sec: 1200
