runtime: python
env: flex
instance_class: F1
entrypoint: gunicorn -b :$PORT application:app
runtime_config:
  python_version: 3.7
resources:
 cpu: 1
 memory_gb: 1.5
 disk_size_gb: 40
readiness_check:
  app_start_timeout_sec: 300
